NREL/REopt_API

summary/views.py
- Adds new financial outputs to the user summary endpoint:
--replacement_costs
--initial_capital_costs_after_incentives
--initial_capital_costs
=> adding summary outputs dependent on nlaws200409

reopt_api/urls.py
bug
invalid resource_uri returned from the outagesimjob endpoint
resource_uri returned from the outagesimjob endpoint is valid
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no
* **Other information**:
=> Add another endpoint for GETing resilience stats

resilience_stats/api.py, resilience_stats/tests/test_new_post_endpoint.py, resilience_stats/views.py
Porting over the bug fixes from `chpbeta` base branch to `develop` branch for the new resilience_stats endpoint. 
* Please wait for the test suite to complete *
=> resil ep fixes ported to develop branch

reo/process_results.py
Porting over bug fix to enable battery dispatch results to be returned
=> fixed battery dispatch in results

reo/src/reopt.jl
fix Julia not reporting battery dispatch in results
=> added storage dispatch to results from julia

reo/src/data_manager.py, reo/src/reopt.jl
- DER export to grid (in NEM and wholesale `SalesTiers`) was not set to zero during `TimeStepsWithoutGrid`.
- removed obsolete `tech_to_tech_class` from data_manager
=> Fix export during outages

reo/nested_inputs.py, reo/src/reopt.jl
DER export to grid (in NEM and wholesale SalesTiers) was not set to zero during TimeStepsWithoutGrid.
removed obsolete tech_to_tech_class from data_manager
=> Merge develop into master 9/2/2020

resilience_stats/views.py
updated handling of cases where outagesim results are not ready
=> outage sim hotfix 09/10/2020

reo/exceptions.py, reo/process_results.py
- Fixes Simple Payback and Irr calcs in reo/process_results.py
- fix bug in upfront_capex_after_incentives
- incorrectly using offtaker discount/tax rates now that O&M costs are assumed to paid by owner
=> 100120 - develop into master - hotfix in api proforma calcs

resilience_stats/views.py
addresses multiple pvs and a division by 0 case in outage simulator inputs
=> fix pv input to outagesim

reo/src/urdb_rate.py, reo/validators.py
adding line to validators so that the URDB_RateValidator sees rates returned from the openei API
require energyratestructure, energyweekendschedule and energyweekdayschedule in a URDB rate
added new checking of URDB float fields
=> Urdb parse

Dockerfile.dev, proforma/proforma_generator.py, reo/exceptions.py, reo/process_results.py, reo/src/reopt.jl, reo/src/wind.py, reo/validators.py
- remove third-party factor from `initial_capital_costs_after_incentives` output
- convert erroneous wind radius to wind diameters
- handle MACRS when analysis years is less than 6 in results processing and proforma
- parse URDB rates to make sure at least an energy rate is supplied
- fix OutOfMemory error in docker containers when building constraints in models that have more than one time step per hour
- create Dockerfile.dev for Kubernetes deploys
=> 201028 master<-develop

reo/nested_inputs.py
Setting new cap on tax rates to avoid a divide by zero in results processing and the proforma
=> update tax pct

julia_envs/Xpress/Manifest.toml
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
* **Other information**:
=> Update Xpress to 0.12

julia_envs/Xpress/Manifest.toml, reopt_api/celery.py
- In non-third party cases the owner tax and discount percents were not saved to the database resulting in inaccurate after incentive cost calculations in the web UI
- Update Xpress.jl to v0.12 (should fix the OOM issues with celery workers)
=> 11162020 - develop into master

reo/scenario.py, reo/src/pvwatts.py
Explicitly catch and report on PVWatts download errors
=> handle PVWatts download error

summary/views.py
Bug fix
If some of the database fields were not populated for a user's run_uuid then the summary endpoint will fail
Null values are provided for missing data when a scenario has a non-optimal status
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
=> Fix summary views

summary/views.py
add a try/except block to get as many summary fields as possible
=> update summary/views.py to return more data when exception occurs

reo/src/load_profile.py, reo/src/load_profile_boiler_fuel.py, reo/src/load_profile_chiller_thermal.py
Rounding annual energy values to avoid lots of unneeded decimals
=> rounding annual energy

reo/models.py
Fixes DB query error with getting production runs prior to v1.4.0
=> fix parsing db records for pre_CHP runs

CHANGELOG.md, summary/views.py
Fixes database query error the occurs when getting production runs created prior to v1.4.0
=> develop > master 20210201

proforma/proforma_generator.py, reo/utilities.py, reo/validators.py, resilience_stats/views.py
`reo`: **Wind** `size_class` was not being set
`proforma`: could not handle runs prior to v1.4.0 with no CHP database entries
`resilience_stats`: could not handle runs prior to v1.4.0 with no CHP database entries
=> hotfix 02022021

CHANGELOG.md, julia_envs/Xpress/modelinputs.json, proforma/proforma_generator.py, reo/utilities.py, reo/validators.py, resilience_stats/outage_simulator_LF.py, resilience_stats/views.py
- `reo`: Fix **Wind** `size_class` was not being set
- `proforma`: Fix could not handle runs prior to v1.4.0 with no CHP database entries
- `resilience_stats`: Fix could not handle runs prior to v1.4.0 with no CHP database entries
- `resilience_stats`: `outage_simulator` returns 100% survivability when chp_kw >= critical_loads_kw
=> develop > master 20210203

CHANGELOG.md, Dockerfile.xpress.pyjul, Dockerfile.xpress.pyjul16rc1, docker-compose.nginx.yml, julia_envs/Xpress/Manifest.toml, nginx/Dockerfile, nginx/nginx.conf, reo/src/pvwatts.py, reo/src/techs.py
- `reo`: Fix **PVWatts** being called when user provides `PV.prod_factor_series_kw`
- `reopt_api`: new `docker-compose.nginx.yml` for standing up the API on a server with remote access (for example if one wants to host the API on a cloud service)
- `reopt_api`: update `Dockerfile.xpress` to use `nlaws/pyjul:1.5.2` base image (was using Julia 1.3)
=> Nginx docker-compose, PVWatts bug fix

reo/src/load_profile.py, reo/validators.py
- `reo`: In `validators.py` catches case where invalid percent_share entry was used in check special cases function
- `reo`: In `loadprofile.py` catches where 0 lat/long was resolving to False and leading to None for lat and long
=> Hotfix022421

.helm/values.production.yaml, Jenkinsfile, requirements.txt
based on cpu usage we can scale up 50-75%.  as we scale up towards full utilization of the Rancher hosts we will also be able to better understand how high we can set the user POST rate limits.
also:
- Bump django from 3.1.7 to 3.1.8
- typo fix in Jenkinsfile
=> master<-dev 21.04.13 Julia pods 10->15

julia_src/http.jl, reo/src/run_jump_model.py
Julia exceptions are less generic now.
=> Log more info for errors in Julia code

julia_src/Manifest.toml, julia_src/http.jl, reo/validators.py, requirements.txt
- addresses https://github.com/NREL/REopt_Lite_API/issues/223
- improved Julia API exception handling
- bug fix in Validator
=> Master <- Develop update HTTP.jl, better Julia exception handling

docker-compose.cbc.yml, julia_src/Dockerfile.cbc, julia_src/cbc/Manifest.toml, julia_src/cbc/Project.toml, julia_src/cbc/REopt.jl, julia_src/cbc/cbc_model.jl, julia_src/cbc/http.jl, julia_src/cbc/precompile.jl, julia_src/http.jl
- one bug fix in julia_src/http.jl
- add Docker files to support hosting the API using Cbc
=> add Cbc Docker set up, fix error message handling in http.jl

julia_src/reopt_model.jl, reo/exceptions.py
- bug fix: exports into the wholesale bin were limited to the BAU annual electricity consumption
- bug fix: the bigM constraints for simultaneous export/import could be violated by choosing `binNoGridPurchases=1.00001` (a valid value given the tolerance). these constraints are now implemented using indicators
=> remove wholesale export limit, fix simul. ex/import constraints

ghpghx/models.py, proforma/proforma_generator.py
- Remove deprecated emissions outputs from proforma_generator
- Sync up 2 climate zones mapping for GHP (change 7a and 7b to 7 and 8)
=> Proforma fix

proforma/proforma_generator.py
Hot fix: fix proforma to handle NO GHP runs
=> Fix proforma to handle NO GHP

requirements.txt
security patch
dependabot alert
upgrade packages to versions that patch security risk
no
=> update requirements.txt for security patches

julia_src/Manifest.toml
Update REopt.jl in /julia_src to v0.20.0 which includes `Boiler` (was NewBoiler in API) and `SteamTurbine` techs.
=> Update REopt.jl to v0.20.0

julia_src/Manifest.toml
This updates REopt.jl to the latest version which includes Heating and Cooling Load time series outputs.
=> Update REoptJL and other package dependencies

CHANGELOG.md
See PR https://github.com/NREL/REopt_API/pull/389 for hotfix.
=> Fix /futurecost endpoint URL routing issue

CHANGELOG.md, resilience_stats/api.py, resilience_stats/tests/ERP_opt_post.json, resilience_stats/tests/test_erp.py
=> default ERP max_outage_duration to max in outage_durations

CHANGELOG.md, resilience_stats/models.py
Bug fix
ERP posts from UI to /erp endpoint returned the following errors:
"op_avail() takes 3 positional argument but 4 were given"
"mttf() takes 3 positional argument but 4 were given"
datatype mismatch error
No.
=> Update ERP PrimeGen Input Types

CHANGELOG.md, job/test/test_validator.py, job/validators.py
Bug fix
rooftop fixed PV tilt default is site latitude
rooftop fixed PV tilt default is 10 degrees
provide PV tilt input if not already
=> Fix PV tilt defaulting for rooftop fixed

CHANGELOG.md
=> replace develop with new version num

julia_src/Manifest.toml, reoptjl/test/test_job_endpoint.py, resilience_stats/tests/test_erp.py
Did `Pkg.update("REopt")` and it updated other packages as well.
=> Update REopt.jl to v0.32.5

julia_src/Manifest.toml, julia_src/http.jl, reoptjl/test/test_job_endpoint.py, reoptjl/views.py
This fixes the monthly cooling load issue with /simulated_load, and it makes sure all vectors are converted to vector{Float64} in /simulated_load.
We need to change REopt.jl back to the registered version once we register the changes in REopt.jl.
=> Fix monthly sim load

julia_src/Manifest.toml
=> Reopt.jl V0.32.7

reo/scenario.py, reopt_api/urls.py, reoptjl/test/test_http_endpoints.py, reoptjl/test/test_job_endpoint.py, resilience_stats/tests/test_erp.py
BREAKING official release of the V3 API as the stable version
=> Change /stable to /v3, remove /v3 from /dev, update tests /dev -> /v3

CHANGELOG.md, reo/scenario.py, reopt_api/urls.py, reoptjl/test/test_http_endpoints.py, reoptjl/test/test_job_endpoint.py, resilience_stats/tests/test_erp.py
BREAKING official release of the V3 API as the stable version
=> BREAKING official release of the V3 API as the stable version

reoptjl/views.py
Update the /summary endpoints with GHP for the web tool.
=> Add ghp summary v3

julia_src/Manifest.toml, reoptjl/test/test_http_endpoints.py
Las Vegas was not copied over from v2
=> Add LasVegas to v3 ElectricLoads

CHANGELOG.md, julia_src/Manifest.toml
PR https://github.com/NREL/REopt_API/pull/538
=> No Min Turndown for CHP during outages

CHANGELOG.md
PR: https://github.com/NREL/REopt_API/pull/540
=> Ignore CHP unavailability during multiple outages

reoptjl/validators.py
Fix error when validating multiple/list PVs in reoptjl/v3 app.
=> Fix multiple PV validation

reoptjl/validators.py
See PR https://github.com/NREL/REopt_API/pull/546
=> Hot Fix Multiple PV Validation

julia_src/Manifest.toml
Update REopt.jl to v0.38.1
- See REopt.jl PR https://github.com/NREL/REopt.jl/pull/327
=> Update REopt.jl to v0.38.1

reoptjl/api.py
Update to REopt.jl v0.38.1 to Fix CHP Standby Charges
=> REopt.jl v0.38.1 Fix CHP Standby Charges

CHANGELOG.md, julia_src/Manifest.toml, reoptjl/api.py, reoptjl/test/test_http_endpoints.py
- PR https://github.com/NREL/REopt_API/pull/572
=> REopt.jl v0.43.0

CHANGELOG.md
PR: 
- https://github.com/NREL/REopt_API/pull/607
=> Update REopt.jl to v0.48.1

julia_src/Manifest.toml
See PR:
- https://github.com/NREL/REopt.jl/pull/468
=> Hot Fix: Update REopt.jl to v0.49.1 to avoid common error

julia_src/Manifest.toml
See PR:
- https://github.com/NREL/REopt.jl/pull/503
=> Fix Cost Curve Segments for No-Incentive CapEx Calc
