NREL/REopt_API

reo/src/reopt.jl, reo/src/utils.jl
- Parameter struct now accepts keyword args 
- now filtering the input dict from python to only contain the field names of Parameter struct
- makes calling Parameter more robust
- TODO: currently printing warning when input dict is missing a field name for Parameter struct, this should be a log statement
- refactored `build_params` to `Parameter`
=> refactor Parameter struct to kwdef

reo/src/load_profile.py
@NLaws - I am porting over changes one by one for different features/fixes. This one brings the fix for handling the financial scenario's critical load kw series for the case when the user has uploaded one.
*Please wait for the tests suite to complete before merging*
=> handle uploaded critical load profile in financial case

reo/src/load_profile.py, reo/src/outage_costs.py
@NLaws - this one enables the modeling of existing diesel generator for the financial case's outage simulation.
=> Enable existing diesel gen for financial outage sim

reo/src/reopt.jl
split the ~900 line `reopt_run` function into many smaller functions in order to decrease model build time
=> reopt.jl refactor

reo/src/run_jump_model.py
Optimization timeouts lead to an exception from JuMP when a mosel model times out. This change now raises the existing `OptimizationTimeout` Exception class to appropriately handle the error.
=> Workaround for DimensionMismatch time out bug

resilience_stats/api.py, resilience_stats/tests/test_new_post_endpoint.py, resilience_stats/views.py
feature - return a descriptive error msg to the user when the resilience_stats POST end-point is hit more than once using the same run_uuid || bug - raise the error properly
The code tries to create more than one ResilienceModel for the same run_uuid, prompting database to error out. 
When a duplicate POST (i.e. a post with same run_uuid that has been sent earlier) comes in, it catches the problem in a try block by checking for the ResilienceModel and sends an error message back. 
* **Does this PR introduce a …
=> Resil endpoint fixes

reo/process_results.py, reo/src/reopt.jl, reo/tests/posts/test_curtailment_POST.json, reo/tests/test_curtailment.py
This fixes a bug in curtailment tracking for PV and wind technologies.
Currently curtailment is grouped together with grid sales.  In output processing, these are separated during outage periods, but it is possible to curtail outside of these hours if sales limits are met or export rates are negative.
Curtailment is now populated separately in the JuMP results, and postprocessing has been edited to ensure separate tracking throughout the entire year..  A test has been added to ensure that curtailment takes …
=> Fix curtailment and wind-to-battery tracking

reo/src/data_manager.py, reo/src/urdb_parse.py, reo/tests/test_curtailment.py
- When the wholesale rate is zero, all excess production is forced into curtailment bin by setting the wholesale rate to -1,000 $/kWh
- reo.tests.test_curtailment updated 
- the test was not accounting for excess PV and wind that was being exported to the grid, which was an arbitrary choice since export and curtailment came at zero cost
- rm obsolete tech_to_load from data_manager
- rm obsolete 'util' tech from data_manager
=> Export clarifications

reo/validators.py
In non-third party cases the owner tax and discount percents were not saved to the database resulting in inaccurate after incentive cost calculations in the web UI
=> update validation of owner financials in non-third party cases

reo/process_results.py, reo/validators.py, resilience_stats/api.py
Saving avoided outage costs in the Financial Model to preserve backwards compatibility
Adding deprecation message for this functionality
Note: I moved the deprecation messages to the validator because before we were saving two versions of the warnings message in the db. This way we only save one version of the warnings message because we add the deprecations before initially saving to the database.
=> updated avoided outage cost calc and decprecation message

reo/models.py, reo/process_results.py, reo/validators.py
- [na] Tests for the changes have been added (for bug fixes / features)
- [na] Docs have been added / updated (for bug fixes / features)
Bug fix
reo/api.py saves the input_dict to the database with all values in reo/nested_inputs.py. However, `outage_start/end_hour` are no longer in the database but we have kept them in accepted inputs for backwards compatibility. So when api.py tries to save the inputs to the database it fails due to the missing fields for `outage_start/end_hour`.
The `outage_start/end_hour` …
=> fix outage_start/_end_hour inputs

resilience_stats/views.py
Addresses error in BAU case in resilience_stats endpoint when trying to parse a non-existent BAU avoided outage cost key
=> catch bau error in resilience_stats

CHANGELOG.md, Jenkinsfile, reo/validators.py
- `resilience_stats`: Catch BAU cases and do not calculate avoided outage costs
- `summary`: Catch jobs that resulted in an error and do not parse results, but send run_uuid's back for these jobs
=> develop into master - 20210107

reo/models.py, reo/nested_inputs.py, reo/process_results.py, reo/scenario.py, reo/src/data_manager.py, reo/validators.py
- `reo`: Catch issue in `process_results.py` where `renewable_electricity_energy_pct` is not explicitly set to _None_
- `reo`:  Catch case where `CHP` `prime_mover` is not set and not all required fields are filled in
- `reo`:  Catch issues with `itc_unit_basis` when the ITC is 100%
- `validators.py`: Fix bug where length of percent_share != length of doe_reference_name even though no percent_share is provided (in `LoadProfileBoilerFuel`)
=> Address rollbar issues

reo/src/pvwatts.py
The PVWatts warning about being outside the US may have changed, so there is no trigger to tell the API to use the international dataset. We now use the international dataset if the site is outside the bounds of the NSRDB https://nsrdb.nrel.gov/
=> address international pvwatts bug

reo/src/load_profile.py, reo/src/load_profile_chiller_thermal.py, reo/tests/test_heating_and_cooling_profiles.py, reo/tests/test_hybridloads_heat_cool.py
Change cooling load behavior for when CRB's are used with NO annual_tonhour, which is a common use case because cooling electric load is not normally metered:
- To avoid the issue of the cooling electric load being greater than the total electric load (non-sense) based on user-input/CRB inconsistency, we use the weighted average fraction of total electric for the cooling load buildings and apply that to the total electric load.
=> Ghp hybridloads

docker-compose.yml, julia_src/Dockerfile, julia_src/docker-compose.yml, julia_src/xpress/install.sh, julia_src/xpress/licenseserver/Dockerfile, julia_src/xpress/licenseserver/install.sh
- updated the install.sh and tar file for Xpress v8.8
- hope that updating Xpress will alleviate our memory consumption issue (will update to the latest v8.12 as soon as we can get it)
- not sure how this changed (seems like a Docker change and not related to xpress), but now specifying a build `ARG`  in the docker compose files for the xpress license server name. It used to work to specify the `service` name for the license server; now it appears that one must specify the container name for the license server
=> upgrade xpress from 8.0 to 8.8

.helm/values.production.yaml, CONTRIBUTING.md, reo/nested_inputs.py, reo/tests/posts/noTechs_POST.json, reo/tests/test_heating_and_cooling_profiles.py, requirements.txt
Change `optimality_tolerance_[bau and techs]` (MIPRELSTOP) min and max values in `nested_inputs.py`:
1. `min`: change from 1e-5 to 1e-4 (0.0001), which is also the default MIPRELSTOP in Xpress
2. `max`: change from 10 (non-sensical, 1000%) to 0.05 (5%)
I had to simplify the POST for `test_heating_and_cooling_profiles` which had an `optimality_tolerance_techs` of 0.7 because it was timing out with 0.05 - these changes were inconsequential to the features that were being checked in the unit tests.
=> Change optimality_tolerance min and max values

reo/validators.py
Bug fix for inputs validation of heating load (`LoadProfileBoilerFuel`). The API was erroneously giving an `input_error` if a custom 8760 heating load (`LoadProfileBoilerFuel.loads_mmbtu_per_hour`) was supplied and the `doe_reference_name` for `LoadProfile` or `LoadProfileBoilerFuel` **not** supplied. We don't need `doe_reference_name` if the 8760 profile is supplied.
This PR addresses this [Pivotal Story](https://www.pivotaltracker.com/n/projects/1909317/stories/180319110).
=> Fix validation to allow LoadProfileBoilerFuel .loads_mmbtu_per_hour

julia_src/reopt_model.jl
Major CHP bug hot fix: CHP variable (production-based) O&M is being double-counted (twice as high as it should be). This change fixes that, and makes the reopt_model.jl code more concise.
=> Fix double-counting CHP prod-based O&M cost

reo/process_results.py, reo/tests/test_re_emissions_constraints.py, reo/tests/test_steamturbine.py
- [N/A ] Docs have been added / updated (for bug fixes / features)
Bug fix for scenarios in which emissions are equal in the BAU and Optimized cases (e.g. system is sized but not dispatched). These scenarios and off grid runs now report "None" for the output "breakeven_cost_of_emissions_reduction_us_dollars_per_tCO2" 
Div by Zero error. 
These scenarios and off grid runs now report "None" for the output "breakeven_cost_of_emissions_reduction_us_dollars_per_tCO2" 
No.
=> Divbyzero fix

CHANGELOG.md, reo/models.py, reo/nested_inputs.py, reo/tests/test_coincident_peak.py, reo/validators.py
bug fix
When a 2D list was provided for coincident_peak_load_active_timesteps, and it had float values in it that were invalid time steps (e.g 1.2), the validator would not return an error. In the JuMP model, the floats would be used as indices and result in a REoptFailedToStart error for the user. When a 2D list provided had float values but they were integers in float form (e.g. 1.0), the validator would not convert these to integers, resulting also in a REoptFailedToStart error.
Any time float values are provided in coincident_peak_load_active_timesteps, the validator converts them to integers if possible otherwise gives the input error "Could not convert coincident_peak_load_active_timesteps (<value>) in …
=> Fix validator bug where list_of_list conversion didn't capture inner list type

reo/src/data_manager.py
bug fix
Units of CHP om_cost_us_dollars_per_hr_per_kw_rated are incorrectly converted when it's already the correct units
the CHP O&M om_cost_us_dollars_per_hr_per_kw_rated given to the optimization model is in units of dollars per hr per kw
no
=> correct CHP O&M cost per hr per kw bug

CHANGELOG.md, reo/validators.py
- [all existing tests passed ] Tests for the changes have been added (for bug fixes / features) 
- [n/a - inputs now align with docs ] Docs have been added / updated (for bug fixes / features)
Update to diesel fuel burn rate inputs.
Previously:  Overrode user inputs of 0 for `fuel_slope_gal_per_kwh` and `fuel_intercept_gal_per_hr` with default values. This prevented users from ever entering 0 for these values (which is only an issue for fuel_intercept). Users were not notified of this override.
User inputs for `fuel_slope_gal_per_kwh` and `fuel_intercept_gal_per_hr` will be used. Default values are 0.076 and 0, respectively.
Yes. …
=> remove override of fuel_slope and fuel_intercept

.github/workflows/pull_request_tests.yml, .github/workflows/push_tests.yml, CHANGELOG.md
updates GitHub workflows for pushes and PRs
triggering built in test workflows unnecessarily or duplicates
a push to a branch with a PR triggers push tests to run but not PR tests to run
pushes that only change markdown files don't trigger tests to run
no
=> avoid triggering duplicate github workflows

CHANGELOG.md, reopt_api/urls.py, resilience_stats/tests/test_new_post_endpoint.py
bug fix
the v2/outagesimjob and v2/ghpghx urls are not made available to access the OutageSimJob() and GHPGHXJob() tasks
the v2/outagesimjob and v2/ghpghx urls are added
no
=> add v2/outagesimjob and v2/ghpghx urls

proforma/models.py
Hot fix for proforma download bug, as suggested by Nick M.
Instead of os.mkdir, to recursively create directory for leaf
=> Change Proforma directory creation to os.makedirs

job/test/test_http_endpoints.py, job/urls.py, job/views.py, julia_src/http.jl
Edit endpoints to create a working v3 version
=> endpoints edits for v3

.github/disabled_cbc_workflows/push_test_cbc.yml, .github/workflows/pull_request_tests.yml, .github/workflows/push_tests.yml, CHANGELOG.md
Updated ubuntu-18.04 to ubuntu-latest in GitHub push/pull tests because 18.04 was deprecated in GitHub Actions
all GitHub actions are automatically cancelled during "awareness brownouts" and will soon always fail
github actions run again
no
=> change ubuntu-18.04 to ubuntu-latest in github actions

CHANGELOG.md, job/urls.py
Reuse the same `reo` view `schedule_stats` function for `/dev/schedule_stats` because this endpoint is purely a user-interface helper endpoint.
=> Add /dev/schedule_stats endpoint

.helm/values.production.yaml, julia_src/http.jl
- Increase JuliaMemoryLimit to 16GB, with still a base request of 8GB
- Implement Bhavesh's "empty!(model)" strategy for releasing memory
=> Increase julia mem and empty! model

job/views.py
Bugs
Currently, the focus gets set incorrectly based on comparison to None,and CHP/prime generator size is not returned.
Focus now gets set on length of outage time steps field and chp/prime generator size gets returned in summary if it was run.
No
=> Update focus logic and add chp_kw sizes

job/views.py
add prime_gen_kw and logic for setting that value.
Bug fix
Currently, prime_gen_kw value is returned under the chp_kw key with no way to distinguish the tech being modeled via this value
Now, prime_gen_kw represents prime generator kW whereas chp_kw represents chp kW
No
=> Add prime_gen_kw output and logic

job/validators.py
Fixes validation bug and improves DRY.
Validation bug:
If a user input a SpaceHeatingLoad or DomesticHotWaterLoad input of fuel_loads_mmbtu_per_hour, which should not require a doe_reference_name, the validator was checking for and requiring a doe_reference_name to be there too.
=> Fuel loads profile input fix

job/validators.py
See https://github.com/NREL/REopt_API/pull/469.
Fixes validation bug and improves DRY.
Validation bug:
If a user input a SpaceHeatingLoad or DomesticHotWaterLoad input of fuel_loads_mmbtu_per_hour, which should not require a doe_reference_name, the validator was checking for and requiring a doe_reference_name to be there too.
=> Hot fix: Fuel loads profile input

CHANGELOG.md, julia_src/http.jl
bug fix
`simulated_load` throws an error in cooling load for blended reference buildings, type mismatch with REopt.jl requirements
`cooling_pct_share` now is converted to a vector of floats in the `simulated_load` function within http.jl
=> convert cooling_pct_share to floating point numbers in http.jl simulated_load

julia_src/http.jl, reoptjl/src/process_results.py
Hot fix for adding `ExistingChiller.cop` to API response inputs when relying on REopt.jl logic for the default value (dependent on cooling load).
=> Update ExistingChiller cop inputs from Julia

CHANGELOG.md, julia_src/http.jl, reoptjl/test/test_http_endpoints.py, reoptjl/test/test_job_endpoint.py, reoptjl/urls.py, reoptjl/views.py
Feature
No endpoint to call Julia to obtain existing chiller COP when pre-populating database (this can be done after the solve)
new HTTP endpoint `get_existing_chiller_default_cop` performs this task, which allows for access to UI when generating uploaded cooling loads 
No
=> Add endpoint get_existing_chiller_default_cop

CHANGELOG.md, reoptjl/test/test_http_endpoints.py, reoptjl/views.py
Bug fix
The `get_existing_chiller_default_cop` endpoint only accepts posts with every key populated
- The `get_existing_chiller_default_cop` endpoint now had all optional inputs; default values are already in place in REopt.jl in the event that `None`/`nothing` is passed to Julia.  **edit 9/7: a default is now in place for the max thermal factor.**
- A new test shows that when no inputs are provided the "unknown" chiller default cop is returned.
- The thermal max load input is in tons, rather than kW; the unit conversion is then performed in the API before calling the REopt.jl function (which converts back to tons).  
No breaking changes
This should allow for only `max_load_kw` or `max_load_kw_thermal` but not both to be populated in UI calls (which are necessary for the populating …
=> Update chiller cop call

reopt_api/urls.py, reoptjl/api.py
Add the /v3 URLs which copies over all the /dev URLs from the reoptjl app (futurecosts app will stay in /dev).
This has been tested against the erp-v3 webtool locally with /dev changed to /v3 for all API calls.
=> Add v3 URLs

.helm/values.production.yaml, .helm/values.yaml
For a REopt run with BAU and Optimal, we only use one celery pod instead of two
Each Julia pod will now do threading to use 2 CPU for parallel BAU and Optimal cases, so we increase the CPU there.
We only need 10 Julia (and 10 celery) pods to maintain current parallel processing of runs.
I kept an extra 5 (for a total of 15) Julia pods for those to process endpoints which are largely served through the HTTP.jl server in the Julia pods.
=> Increase Julia pod CPU, decrease celery and Julia count for V3

CHANGELOG.md, reoptjl/models.py, reoptjl/test/posts/all_inputs_test.json, reoptjl/test/posts/off_grid_validations.json, reoptjl/test/posts/outage.json, reoptjl/test/test_job_endpoint.py, reoptjl/test/test_validator.py, reoptjl/validators.py
Annual update to default values in REopt. Updated to reflect the latest available data (largely, cost data). 
Users will get different results due to updates to defaults. Users can override default values with old values to obtain the same results. See table below. 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/afarthin/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/c …
=> Defaults updates fy23

CHANGELOG.md, julia_src/Manifest.toml, julia_src/http.jl, reoptjl/test/test_http_endpoints.py
fix handling of `is_electric_only` in the `/chp_defaults` endpoint to allow for prime generator inputs to be retrieved
=> process is_electric_only in /chp_defaults endpoint

reoptjl/test/test_http_endpoints.py, reoptjl/views.py
Fixes bug in obtaining CHP defaults using django to call the endpoint instead of calling it directly.
parameter `is_electric_only` is not added to inputs when calling http.jl from django, leading to a default value of `"false"`
`is_electric_only = "true"` is now appropriately received by the API, so Prime Generator technologies are created with appropriate adjustments to capital costs and tax incentives.
No
=> Fix chp defaults view

julia_src/Manifest.toml
Consistent with V2, we do not want to enforce `min_turn_down_fraction` for `CHP` during multiple/stochastic outages
=> No Min Turndown for CHP during outages

julia_src/Manifest.toml, reoptjl/test/test_job_endpoint.py
Currently, inconsistent with the deterministic single outage scenario which ignores CHP unavailability during the outage, the stochastic multiple outages was not ignoring CHP unavailability. This PR changes that to ignore CHP unavailability during the outages, while preserving the unavailability periods for the 8760 grid-tied operation. This allows consistency in the economic dispatch between non-outages and outages scenarios.
=> Ignore CHP unavailability during multiple outages

README.md, julia_src/Manifest.toml, reoptjl/api.py, reoptjl/test/test_job_endpoint.py
This fixes a discrepancy between the load profile and the year used for the CHP unavailability -> production factor, for electric-only CHP (Prime Generator)
=> Hot Fix: add year for electric-only CHP unavailability profile

CHANGELOG.md, julia_src/highs/Manifest.toml, julia_src/xpress/Manifest.toml, reoptjl/api.py, reoptjl/views.py
- Fixes an error from the /summary endpoint for off-grid evaluations when there is no ElectricTariffInputs
- Updates REopt.jl for the HiGHS solver environment
=> Fix summary endpt

CHANGELOG.md, reoptjl/validators.py, resilience_stats/api.py
You previously could not run a Wind eval for a location outside of the WindToolkit bounds (e.g. international locations), due to the Wind validation code.  This PR fixes this. 
- I also updated the REopt.jl version in the meta data of the ERP code
=> allow international wind

CHANGELOG.md, resilience_stats/models.py, resilience_stats/tests/test_erp.py
Bug fix
Divide by zero error when POSTing to the `/erp` endpoint with a `battery_size_kw` of 0
When `battery_size_kw` is 0, the `num_battery_bins` default is 1
No
=> ERP bug fix: divide by zero BESS

julia_src/Manifest.toml, reoptjl/api.py, reoptjl/test/test_http_endpoints.py
See PR's from REopt.jl here:
https://github.com/NREL/REopt.jl/pull/364
From REopt.jl CHANGELOG:
- `simple_payback_years` calculation when there is export credit
- Issue with `SteamTurbine` heuristic size and default calculation when `size_class` was input
- BAU emissions calculation with heating load which was using thermal instead of fuel
=> REopt.jl v0.43.0

CHANGELOG.md, julia_src/Manifest.toml, julia_src/http.jl, reoptjl/api.py, reoptjl/views.py
- Update Big M constraints to address bugs after indicator -> Big M conversions
- https://github.com/NREL/REopt.jl/pull/401 
- Add `thermal_efficiency` as input to /chp_defaults endpoint to handle custom CHP prime movers which cannot normally supply steam
- https://github.com/NREL/REopt.jl/pull/415
=> Big M Constraint Updates, addition to /chp_defaults

CHANGELOG.md, reoptjl/test/test_http_endpoints.py, resilience_stats/tests/test_erp.py, resilience_stats/urls_v3plus.py, resilience_stats/views.py
feature
no erp/inputs (same as erp/help) or erp/outputs urls in the API
erp/inputs (same as erp/help) or erp/outputs urls added
no
once merged, update wiki adding 
Get descriptions of possible ERP inputs: /erp/inputs?
Get descriptions of possible ERP outputs: /erp/outputs?
here:
https://github.com/NREL/REopt_API/wiki/1.-Structure-of-the-REopt-API#api-endpoints
=> erp outputs endpoint

CHANGELOG.md, julia_src/http.jl, reoptjl/api.py, reoptjl/models.py, reoptjl/src/run_jump_model.py, reoptjl/test/test_job_endpoint.py, resilience_stats/api.py, resilience_stats/models.py, resilience_stats/tests/test_erp.py, resilience_stats/urls_v3plus.py, resilience_stats/views.py
feature, robustness
see #589 and #593 
see #589 and #593 
no
=> ERP outputs endpoint; set reopt_version in meta data programmatically

reoptjl/views.py
Fix a few bugs and cover a gap in re-linking portfolios and runs.
Bug fix
Runs cannot be unlinked; once a run is unlinked from a portfolio, it cannot be re-linked to that portfolio.
Runs can be unlinked and successfully relinked to portfolios
No
=> Bug fix and cover a gap

julia_src/Dockerfile
The underlying SSL issue appears to be tied to libgit2 library being unable to read a PEM file format, and hence errors. Workaround is to use
=> workaround fix for SSL issue

reoptjl/custom_table_config.py
Bug fix for results table links
The current link points to the staged url that was previously used for testing
The fix will redirect the results link to the live reopt version
No changes will be necessary, although users may need to re-download the results table
=> fix to correct results link in results table

CHANGELOG.md, julia_src/Manifest.toml
Update REopt.jl to v0.48.1 with these updates:
- https://github.com/NREL/REopt.jl/pull/451
=> Update REopt.jl to v0.48.1

CHANGELOG.md, reoptjl/views.py
Feature
A summary run can only have 1 focus (i.e. resilience or financial or clean-energy)
A summary can have all applicable focuses.
No.
=> Return multiple summary focus

reoptjl/src/process_results.py
- Fix issue with CHP.installed_cost_per_kw not being an array when updating the inputs model object (which expects an array) in process_results.py, from Julia.
- For context, we rely on REopt.jl logic to assign CHP defaults, and then we have to update the API model fields after REopt.jl runs, in process_results.py. Since CHP.installed_cost_per_kw can be either a float or an array in REopt.jl, while in the API model field it's processed to always be an array, we need to check and convert to an array if it comes back from REopt.jl as a float.
=> Fix updating CHP.installed_cost_per_kw if scalar

reoptjl/src/process_results.py, reoptjl/test/posts/ashp_defaults_update.json, reoptjl/test/test_job_endpoint.py
- There were extra input fields coming back from REopt.jl for ASHP defaults (fields that were not included in the API, such as `can_serve_process_heat`) and trying to update the Django models for ASHP Inputs with those, and that was causing the update to error silently (within a try except clause)
- This PR prunes any of those extra fields that are not included in the Django model classes before updating the models
=> Fix updating ASHP Inputs defaults from REopt.jl

CHANGELOG.md, reoptjl/src/process_results.py, reoptjl/test/posts/ashp_defaults_update.json, reoptjl/test/test_job_endpoint.py
PRs:
- https://github.com/NREL/REopt_API/pull/613
=> Hot Fix: ASHP defaults updating from REopt.jl

reoptjl/models.py
_Current_:
If a user inputs an `installed_cost_per_kw` for `Wind`, along with a `Wind.size_class`, the `installed_cost_per_kw` value gets overwritten by the default cost value for the `size_class`. The web tool always sends a `size_class`, so currently web tool users **cannot provide a custom input wind installed cost**. 
_Fix_:
This PR fixes this to pass the user-input `installed_cost_per_kw`.
=> Fix for user-input wind installed cost to not be over-written

CHANGELOG.md, julia_src/Manifest.toml
See REopt.jl PR:
- https://github.com/NREL/REopt.jl/pull/505
=> Fix PV size class updating with max size and space available inputs

CHANGELOG.md, load_builder/views.py
- Simplified /ensite UI-to-EnLitePy translation.
- Enforces single keys: pChgMax_kW (vehicles), pChgCap_kW (EMS override).
- Deterministic EMS capacity derivation (sum of charger count * power_kW) when no override.
- Remove ambiguity and unused legacy paths.
- Make max charging power changes reliably propagate.
- Provide on-demand introspection without bloating default responses.
=> Clean EnSite payload builder
